### PR TITLE
Dockerize client

### PR DESCRIPTION
**Pull request by EliasJorgensen**
Client now contains a Dockerfile, which can be used to build an Nginx container, containing the client production build. This is a needed step toward hosting the app on AWS.

A part of issue #11.

### CODE REVIEW

**Comment by EliasJorgensen** [comment]
The `nginx.conf` file contains an outcommented reverse proxy template, in case that we create more docker services, that the client needs to communicate with. If we only use AWS services, this can probably just be removed.

**Comment by Saturate** [comment]
Can we use [Træfik](https://traefik.io) instead of Nginx? I think it has some nice features, and it's very easy to configure.

**Comment by EliasJorgensen** [comment]
I've thought a bit about it, and i'm not sure if we are going to use a Docker image for this, or just use an S3 bucket. It's a bit expensive to run an EC2 instance, just to run an Nginx container. I'll run it by the other folks in the hosting group.

**Comment by EliasJorgensen** [comment]
Build now works, and pushes client image to ECR on build.

**Comment by EliasJorgensen** [comment]
Proof:
image

**Pull request merged**
